{
    lore = ds_list_create();
    var index = 0;
    lore[|index++] = "You find a small box with a silver question mark for a latch. When you pick it up, a memory burns itself awake. You remember being close to an end... You remember the Reaper behind you and the carnage that lay ahead. You sense the box might have helped you, but you chose to leave it behind with a strong sense of purpose.##Do you open the box?";
    lore[|index++] = "You find a rusted box with a silver question mark for a latch. When you pick it up, you have a vision of a terrified man covered with deep claw marks, clutching the box. Panicked, he drops it as Zombies lash out from the shadows. His soul is torn from his body, as his husk joins the the swarm.##Do you open the box?";
    lore[|index++] = "You find a singed box with a silver question mark for a latch. When you pick it up, you have a vision of diminutive winged being, skin twisted and red. It is locked in a heated argument with itself over the reality of its situation. After a confusing exchange of insults at itself, the conclusion is reached: reality is paper-thin, and must be burned.##Do you open the box?";
    lore[|index++] = "You find a small box with a silver question mark for a latch. When you pick it up, you have a vision of a pale blue flame swirling around a set of metal runes. They hover above the ground. Days past as the Lantern Archon bumps the box, unable to open it. Its quest abruptly ends with a shotgun blast from the darkness.##Do you open the box?";
    lore[|index++] = "You find a scratched box with a silver question mark for a latch. When you pick it up, you have a vision of a woman with the head of a beast. She stares at the box in her arms, and recoils when she sees her reflection in the silver latch. Her humanity slips away amongst her sobs, which turn beastly. A slight smile forms and turns to a low snarling laugh. She leaves the box for a more needy soul.##Do you open the box?";
    lore[|index++] = "You find a small box with a silver question mark for a latch. When you pick it up, you have a vision of a glowing figure with a single hand holding the box. A red, ethereal hand appears and reaches through the box, extracting a bright light. The box slams to the ground as the hands disappear.##Do you open the box?";
    lore[|index++] = "You find a small dented box with a silver question mark for a latch. When you pick it up, you have a vision of a twisted, horned man with a shotgun and light armor. The Demon Soldier shoots the box after rounding a corner, instinctively attacking what he did not expect to see. After briefly examining the box, it is decided that it is not a threat. The soldier shoots the box once more for good measure and carries on.##Do you open the box?";
    lore[|index++] = "You find a small box with a silver question mark for a latch. When you pick it up, you have a vision of a radiant figure wreathed in warm light. The Archangel is using the box as a stand for its rifle, calmly firing round after round into the darkness at a slow and deliberate pace.##Do you open the box?";
    lore[|index++] = "You find a small crumpled box with some shattered silver on the ground next to it. When you pick it up, you have a vision of a brilliant golden figure, bathed in light, lying face down in the dirt next to the box. The Seraph grabs the box and embeds it into the skull of a Demon Soldier as the Seraph comes back to its feet.##Do you open the box?";
    lore[|index++] = "You find a small box with a silver question mark for a latch. When you pick it up, you have a vision a powerful demon examining the box. Time seems to fluctuate as it opens, and does not open, the box. The demon who opened the box recoils from a bright light and fades away. The one who didn't, remains. Yet, which is reality?##Do you open the box?";
    lore[|index++] = "You find a blacked box with a silver question mark melted into the side. When you pick it up, you have a vision of a looming tower, burning green-blue flame. The Purifier moves by, causing everything to tremble with its might. The box is nearly destroyed. You watch until all fades away.##Do you open the box?";
    lore[|index++] = "You find a small box with a silver question mark for a latch. When you pick it up, you have a vision of a shadowy figure holding the box. It's silent as it hunts. The Reaper puts the box down carefully, then materializes a massive rifle-cannon from nowhere. Where does it aim?##Do you open the box?";
    lore[|index++] = "You find a battered box with deep claw marks. When you pick it up, you have a vision of formless carnage ripping and clawing violently at the box. It shrieks in rage, unable to rip the box apart, yet never considering that the box could simply be opened. Eventually it gives up, storming off through a wall.##Do you open the box?";
}
