// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // AI_FollowPlayer
global.__objectDepths[1] = 0; // AI_Melee_Player
global.__objectDepths[2] = 0; // AI_Range_Player
global.__objectDepths[3] = 0; // AI_MR_Switch
global.__objectDepths[4] = 0; // AI_Wander
global.__objectDepths[5] = 0; // AI_Spawner
global.__objectDepths[6] = 0; // AI_Component
global.__objectDepths[7] = 0; // Fighter_Component
global.__objectDepths[8] = 0; // Condition_Ambience
global.__objectDepths[9] = 0; // Condition_Background_Locked
global.__objectDepths[10] = 0; // Condition_No_Regeneration
global.__objectDepths[11] = 0; // Condition_No_Perk_Checks
global.__objectDepths[12] = 0; // Condition_Less_XP
global.__objectDepths[13] = 0; // Condition_Darkness
global.__objectDepths[14] = 0; // Condition_Weak_Player_Melee
global.__objectDepths[15] = 0; // Condition_Weak_Player_Ranged
global.__objectDepths[16] = 0; // Condition_Strong_Creature_Ranged
global.__objectDepths[17] = 0; // Condition_Strong_Creature_Melee
global.__objectDepths[18] = 0; // Condition_Scale
global.__objectDepths[19] = 0; // Condition_Uniformity
global.__objectDepths[20] = 0; // Condition_Seeded
global.__objectDepths[21] = 0; // Condition_Player_Perk
global.__objectDepths[22] = 0; // Condition_Creature_Perk
global.__objectDepths[23] = 0; // Arch_Angel
global.__objectDepths[24] = 0; // Mound
global.__objectDepths[25] = 0; // Carnage
global.__objectDepths[26] = 0; // Creature
global.__objectDepths[27] = 0; // Demon_Soldier
global.__objectDepths[28] = 0; // Fiend
global.__objectDepths[29] = 0; // Hound_Archon
global.__objectDepths[30] = 0; // Imp
global.__objectDepths[31] = 0; // Latern_Archon
global.__objectDepths[32] = 0; // Purifier
global.__objectDepths[33] = 0; // Reaper
global.__objectDepths[34] = 0; // Seraph
global.__objectDepths[35] = 0; // Wraith
global.__objectDepths[36] = 0; // Zombie
global.__objectDepths[37] = 0; // Queen
global.__objectDepths[38] = 0; // Larva
global.__objectDepths[39] = -1000; // FX_Ranged
global.__objectDepths[40] = -1000; // FX_Charge
global.__objectDepths[41] = 0; // FX_Trace
global.__objectDepths[42] = 0; // FX_Tentacle
global.__objectDepths[43] = 0; // FX_Storm
global.__objectDepths[44] = -10; // FX_Floating_Text
global.__objectDepths[45] = -11; // FX_Death_Splash
global.__objectDepths[46] = -11; // FX_Death_Fade
global.__objectDepths[47] = 0; // FX
global.__objectDepths[48] = -1; // FX_Burning
global.__objectDepths[49] = -1; // FX_Regen
global.__objectDepths[50] = 0; // FX_Teleport_Target
global.__objectDepths[51] = 0; // FX_Teleport_Source
global.__objectDepths[52] = 0; // Actor
global.__objectDepths[53] = 0; // Boon_Critical_Health_Creatures
global.__objectDepths[54] = 0; // Boon_Learning
global.__objectDepths[55] = 0; // Boon_Full_Heal
global.__objectDepths[56] = 0; // Boon_Pathfinder
global.__objectDepths[57] = 0; // Boon_All_Seeing
global.__objectDepths[58] = 0; // Boon_Flamebearer
global.__objectDepths[59] = 0; // Curse_Critical_Health
global.__objectDepths[60] = 0; // Curse_Forgetful
global.__objectDepths[61] = 0; // Curse_Healthy_Creatures
global.__objectDepths[62] = 0; // Curse_Experienced_Creatures
global.__objectDepths[63] = 0; // Curse_Hunted
global.__objectDepths[64] = 0; // Curse_MadQueen
global.__objectDepths[65] = 0; // Curse_Portal
global.__objectDepths[66] = 0; // Boon
global.__objectDepths[67] = 0; // Curse
global.__objectDepths[68] = 0; // Pandora_Event
global.__objectDepths[69] = 0; // Perk_Background_Sadist
global.__objectDepths[70] = 0; // Perk_Background_Saint
global.__objectDepths[71] = 0; // Perk_Background_Scholar
global.__objectDepths[72] = 0; // Perk_Background_Seeker
global.__objectDepths[73] = 0; // Perk_Background_Simple
global.__objectDepths[74] = 0; // Perk_Background_Forgotton
global.__objectDepths[75] = 0; // Perk_Background_Survivor
global.__objectDepths[76] = 0; // Perk_Background_Slayer
global.__objectDepths[77] = 0; // Perk_Background_Sinner
global.__objectDepths[78] = 0; // Perk_Background_Switch
global.__objectDepths[79] = 0; // Perk_Armored
global.__objectDepths[80] = 0; // Perk_Aura
global.__objectDepths[81] = 0; // Perk_Beserker
global.__objectDepths[82] = 0; // Perk_Blood_Secret_Ritual
global.__objectDepths[83] = 0; // Perk_Brawler
global.__objectDepths[84] = 0; // Perk_Called_Shots
global.__objectDepths[85] = 0; // Perk_Chakra
global.__objectDepths[86] = 0; // Perk_Clairvoyance
global.__objectDepths[87] = 0; // Perk_Darkvision
global.__objectDepths[88] = 0; // Perk_Demon_Armor
global.__objectDepths[89] = 0; // Perk_Ethereal
global.__objectDepths[90] = 0; // Perk_First_Aid
global.__objectDepths[91] = 0; // Perk_Flesh_Guise_Ritual
global.__objectDepths[92] = 0; // Perk_Focused
global.__objectDepths[93] = 0; // Perk_Fury
global.__objectDepths[94] = 0; // Perk_Grace
global.__objectDepths[95] = 0; // Perk_Heartseeker
global.__objectDepths[96] = 0; // Perk_Holy_Fire
global.__objectDepths[97] = 0; // Perk_HP_Boost
global.__objectDepths[98] = 0; // Perk_Inferno_Rounds_Ritual
global.__objectDepths[99] = 0; // Perk_Initiative
global.__objectDepths[100] = 0; // Perk_Insightfull
global.__objectDepths[101] = 0; // Perk_Lifesense
global.__objectDepths[102] = 0; // Perk_Magically_Gifted
global.__objectDepths[103] = 0; // Perk_Marksman
global.__objectDepths[104] = 0; // Perk_Melee_Specialist
global.__objectDepths[105] = 0; // Perk_Open_Minded
global.__objectDepths[106] = 0; // Perk_Pact_Pistol
global.__objectDepths[107] = 0; // Perk_Paradox_Trigger
global.__objectDepths[108] = 0; // Perk_Phoenix_Armor
global.__objectDepths[109] = 0; // Perk_Radiant_Armor
global.__objectDepths[110] = 0; // Perk_Reaper
global.__objectDepths[111] = 0; // Perk_Regeneration
global.__objectDepths[112] = 0; // Perk_Rifle
global.__objectDepths[113] = 0; // Perk_Shadow_Armor
global.__objectDepths[114] = 0; // Perk_Shotgun
global.__objectDepths[115] = 0; // Perk_Sniper_Rifle
global.__objectDepths[116] = 0; // Perk_Solar_Armor
global.__objectDepths[117] = 0; // Perk_Stone_Body_Ritual
global.__objectDepths[118] = 0; // Perk_Storm_Of_Vengance
global.__objectDepths[119] = 0; // Perk_Teleport_Ritual
global.__objectDepths[120] = 0; // Perk_Telescape_Pact
global.__objectDepths[121] = 0; // Perk_Skill_Pact
global.__objectDepths[122] = 0; // Perk_Mindsight_Pact
global.__objectDepths[123] = 0; // Perk_Pact_Ritual
global.__objectDepths[124] = 0; // Perk_Freezing_Pact
global.__objectDepths[125] = 0; // Perk_Tentacle_Whip
global.__objectDepths[126] = 0; // Perk_Unobtainable
global.__objectDepths[127] = 0; // Perk_Void_Armor
global.__objectDepths[128] = 0; // Perk_Volatile_Regeneration_Ritual
global.__objectDepths[129] = 0; // Perk_Wrath
global.__objectDepths[130] = 0; // Water
global.__objectDepths[131] = 0; // Murk
global.__objectDepths[132] = 0; // Lava
global.__objectDepths[133] = 0; // Grass
global.__objectDepths[134] = 0; // Dirt
global.__objectDepths[135] = 0; // Sand
global.__objectDepths[136] = 0; // Snow
global.__objectDepths[137] = 0; // Daylight
global.__objectDepths[138] = 0; // Exit
global.__objectDepths[139] = 0; // Floor
global.__objectDepths[140] = 0; // Lamp
global.__objectDepths[141] = 0; // Lore_Box
global.__objectDepths[142] = 0; // Muzzle_Flash
global.__objectDepths[143] = 0; // Wall
global.__objectDepths[144] = 0; // Teleporter
global.__objectDepths[145] = 0; // Menu_Item_Bug_Report
global.__objectDepths[146] = 0; // Menu_Item_Challenge_Game
global.__objectDepths[147] = 0; // Menu_Item_Challenge_Game_Seeded
global.__objectDepths[148] = 0; // Menu_Item_Close
global.__objectDepths[149] = 0; // Menu_Item_Close_Perk_Help
global.__objectDepths[150] = 0; // Menu_Item_Close_With_Screencap
global.__objectDepths[151] = 0; // Menu_Item_Config_Brightness
global.__objectDepths[152] = 0; // Menu_Item_Config_Debug_Logging
global.__objectDepths[153] = 0; // Menu_Item_Config_Draw_FoW
global.__objectDepths[154] = 0; // Menu_Item_Config_HP_Bar_Color_Shift
global.__objectDepths[155] = 0; // Menu_Item_Config_Show_Alerts
global.__objectDepths[156] = 0; // Menu_Item_Config_Collapse_Event
global.__objectDepths[157] = 0; // Menu_Item_Config_VI_Keyboard
global.__objectDepths[158] = 0; // Menu_Item_Config_Show_Bar_Values
global.__objectDepths[159] = 0; // Menu_Item_Config_Smooth_Rendering
global.__objectDepths[160] = 0; // Menu_Item_Config_Wait_On_FX
global.__objectDepths[161] = 0; // Menu_Item_Config_Full_Screen
global.__objectDepths[162] = 0; // Menu_Item_Divider
global.__objectDepths[163] = 0; // Menu_Item_Do_Not_Open_Lore_Box
global.__objectDepths[164] = 0; // Menu_Item_Exit_Game
global.__objectDepths[165] = 0; // Menu_Item_Full_Heal
global.__objectDepths[166] = 0; // Menu_Item_Select_Tileset
global.__objectDepths[167] = 0; // Menu_Item_Grant_Perk
global.__objectDepths[168] = 0; // Menu_Item_New_Game
global.__objectDepths[169] = 0; // Menu_Item_Open_Character_Sheet
global.__objectDepths[170] = 0; // Menu_Item_Open_Perk_Help_For
global.__objectDepths[171] = 0; // Menu_Item_Open_Perk_Help
global.__objectDepths[172] = 0; // Menu_Item_Open_Conditions_Menu
global.__objectDepths[173] = 0; // Menu_Item_Open_Credits
global.__objectDepths[174] = 0; // Menu_Item_Open_Help
global.__objectDepths[175] = 0; // Menu_Item_Open_Tileset_Menu
global.__objectDepths[176] = 0; // Menu_Item_Open_Highscore
global.__objectDepths[177] = 0; // Menu_Item_Open_Lore_Box
global.__objectDepths[178] = 0; // Menu_Item_Open_Settings
global.__objectDepths[179] = 0; // Menu_Item_Unstable_Portal
global.__objectDepths[180] = 0; // Menu_Item_Win_Game
global.__objectDepths[181] = 0; // Config
global.__objectDepths[182] = 0; // HUD_Game_Staus
global.__objectDepths[183] = 0; // HUD_Player_Status
global.__objectDepths[184] = 0; // HUD_Target_Status
global.__objectDepths[185] = 0; // Log
global.__objectDepths[186] = 0; // Menu
global.__objectDepths[187] = 0; // Menu_Item
global.__objectDepths[188] = 0; // Menu_System
global.__objectDepths[189] = 0; // Object
global.__objectDepths[190] = 0; // Perk
global.__objectDepths[191] = 0; // Player
global.__objectDepths[192] = 0; // Renderer
global.__objectDepths[193] = 0; // Simulation
global.__objectDepths[194] = 0; // Start_Game_Menu
global.__objectDepths[195] = 0; // Start_Challenge_Menu
global.__objectDepths[196] = 0; // Targeting
global.__objectDepths[197] = 0; // Uncarved
global.__objectDepths[198] = 0; // Usable_Object
global.__objectDepths[199] = 0; // Frame_Delay_Light_Updater
global.__objectDepths[200] = 0; // Analytics
global.__objectDepths[201] = 0; // Color_Log
global.__objectDepths[202] = 0; // Debug_Grid_Overlay
global.__objectDepths[203] = 0; // Nemesis
global.__objectDepths[204] = -1; // State_Grid_Overlay
global.__objectDepths[205] = 0; // Condition
global.__objectDepths[206] = 0; // Visibility_Source
global.__objectDepths[207] = 0; // One_Turn_Visibility_Source
global.__objectDepths[208] = 0; // Score_Keeper
global.__objectDepths[209] = 0; // MusicMixer


global.__objectNames[0] = "AI_FollowPlayer";
global.__objectNames[1] = "AI_Melee_Player";
global.__objectNames[2] = "AI_Range_Player";
global.__objectNames[3] = "AI_MR_Switch";
global.__objectNames[4] = "AI_Wander";
global.__objectNames[5] = "AI_Spawner";
global.__objectNames[6] = "AI_Component";
global.__objectNames[7] = "Fighter_Component";
global.__objectNames[8] = "Condition_Ambience";
global.__objectNames[9] = "Condition_Background_Locked";
global.__objectNames[10] = "Condition_No_Regeneration";
global.__objectNames[11] = "Condition_No_Perk_Checks";
global.__objectNames[12] = "Condition_Less_XP";
global.__objectNames[13] = "Condition_Darkness";
global.__objectNames[14] = "Condition_Weak_Player_Melee";
global.__objectNames[15] = "Condition_Weak_Player_Ranged";
global.__objectNames[16] = "Condition_Strong_Creature_Ranged";
global.__objectNames[17] = "Condition_Strong_Creature_Melee";
global.__objectNames[18] = "Condition_Scale";
global.__objectNames[19] = "Condition_Uniformity";
global.__objectNames[20] = "Condition_Seeded";
global.__objectNames[21] = "Condition_Player_Perk";
global.__objectNames[22] = "Condition_Creature_Perk";
global.__objectNames[23] = "Arch_Angel";
global.__objectNames[24] = "Mound";
global.__objectNames[25] = "Carnage";
global.__objectNames[26] = "Creature";
global.__objectNames[27] = "Demon_Soldier";
global.__objectNames[28] = "Fiend";
global.__objectNames[29] = "Hound_Archon";
global.__objectNames[30] = "Imp";
global.__objectNames[31] = "Latern_Archon";
global.__objectNames[32] = "Purifier";
global.__objectNames[33] = "Reaper";
global.__objectNames[34] = "Seraph";
global.__objectNames[35] = "Wraith";
global.__objectNames[36] = "Zombie";
global.__objectNames[37] = "Queen";
global.__objectNames[38] = "Larva";
global.__objectNames[39] = "FX_Ranged";
global.__objectNames[40] = "FX_Charge";
global.__objectNames[41] = "FX_Trace";
global.__objectNames[42] = "FX_Tentacle";
global.__objectNames[43] = "FX_Storm";
global.__objectNames[44] = "FX_Floating_Text";
global.__objectNames[45] = "FX_Death_Splash";
global.__objectNames[46] = "FX_Death_Fade";
global.__objectNames[47] = "FX";
global.__objectNames[48] = "FX_Burning";
global.__objectNames[49] = "FX_Regen";
global.__objectNames[50] = "FX_Teleport_Target";
global.__objectNames[51] = "FX_Teleport_Source";
global.__objectNames[52] = "Actor";
global.__objectNames[53] = "Boon_Critical_Health_Creatures";
global.__objectNames[54] = "Boon_Learning";
global.__objectNames[55] = "Boon_Full_Heal";
global.__objectNames[56] = "Boon_Pathfinder";
global.__objectNames[57] = "Boon_All_Seeing";
global.__objectNames[58] = "Boon_Flamebearer";
global.__objectNames[59] = "Curse_Critical_Health";
global.__objectNames[60] = "Curse_Forgetful";
global.__objectNames[61] = "Curse_Healthy_Creatures";
global.__objectNames[62] = "Curse_Experienced_Creatures";
global.__objectNames[63] = "Curse_Hunted";
global.__objectNames[64] = "Curse_MadQueen";
global.__objectNames[65] = "Curse_Portal";
global.__objectNames[66] = "Boon";
global.__objectNames[67] = "Curse";
global.__objectNames[68] = "Pandora_Event";
global.__objectNames[69] = "Perk_Background_Sadist";
global.__objectNames[70] = "Perk_Background_Saint";
global.__objectNames[71] = "Perk_Background_Scholar";
global.__objectNames[72] = "Perk_Background_Seeker";
global.__objectNames[73] = "Perk_Background_Simple";
global.__objectNames[74] = "Perk_Background_Forgotton";
global.__objectNames[75] = "Perk_Background_Survivor";
global.__objectNames[76] = "Perk_Background_Slayer";
global.__objectNames[77] = "Perk_Background_Sinner";
global.__objectNames[78] = "Perk_Background_Switch";
global.__objectNames[79] = "Perk_Armored";
global.__objectNames[80] = "Perk_Aura";
global.__objectNames[81] = "Perk_Beserker";
global.__objectNames[82] = "Perk_Blood_Secret_Ritual";
global.__objectNames[83] = "Perk_Brawler";
global.__objectNames[84] = "Perk_Called_Shots";
global.__objectNames[85] = "Perk_Chakra";
global.__objectNames[86] = "Perk_Clairvoyance";
global.__objectNames[87] = "Perk_Darkvision";
global.__objectNames[88] = "Perk_Demon_Armor";
global.__objectNames[89] = "Perk_Ethereal";
global.__objectNames[90] = "Perk_First_Aid";
global.__objectNames[91] = "Perk_Flesh_Guise_Ritual";
global.__objectNames[92] = "Perk_Focused";
global.__objectNames[93] = "Perk_Fury";
global.__objectNames[94] = "Perk_Grace";
global.__objectNames[95] = "Perk_Heartseeker";
global.__objectNames[96] = "Perk_Holy_Fire";
global.__objectNames[97] = "Perk_HP_Boost";
global.__objectNames[98] = "Perk_Inferno_Rounds_Ritual";
global.__objectNames[99] = "Perk_Initiative";
global.__objectNames[100] = "Perk_Insightfull";
global.__objectNames[101] = "Perk_Lifesense";
global.__objectNames[102] = "Perk_Magically_Gifted";
global.__objectNames[103] = "Perk_Marksman";
global.__objectNames[104] = "Perk_Melee_Specialist";
global.__objectNames[105] = "Perk_Open_Minded";
global.__objectNames[106] = "Perk_Pact_Pistol";
global.__objectNames[107] = "Perk_Paradox_Trigger";
global.__objectNames[108] = "Perk_Phoenix_Armor";
global.__objectNames[109] = "Perk_Radiant_Armor";
global.__objectNames[110] = "Perk_Reaper";
global.__objectNames[111] = "Perk_Regeneration";
global.__objectNames[112] = "Perk_Rifle";
global.__objectNames[113] = "Perk_Shadow_Armor";
global.__objectNames[114] = "Perk_Shotgun";
global.__objectNames[115] = "Perk_Sniper_Rifle";
global.__objectNames[116] = "Perk_Solar_Armor";
global.__objectNames[117] = "Perk_Stone_Body_Ritual";
global.__objectNames[118] = "Perk_Storm_Of_Vengance";
global.__objectNames[119] = "Perk_Teleport_Ritual";
global.__objectNames[120] = "Perk_Telescape_Pact";
global.__objectNames[121] = "Perk_Skill_Pact";
global.__objectNames[122] = "Perk_Mindsight_Pact";
global.__objectNames[123] = "Perk_Pact_Ritual";
global.__objectNames[124] = "Perk_Freezing_Pact";
global.__objectNames[125] = "Perk_Tentacle_Whip";
global.__objectNames[126] = "Perk_Unobtainable";
global.__objectNames[127] = "Perk_Void_Armor";
global.__objectNames[128] = "Perk_Volatile_Regeneration_Ritual";
global.__objectNames[129] = "Perk_Wrath";
global.__objectNames[130] = "Water";
global.__objectNames[131] = "Murk";
global.__objectNames[132] = "Lava";
global.__objectNames[133] = "Grass";
global.__objectNames[134] = "Dirt";
global.__objectNames[135] = "Sand";
global.__objectNames[136] = "Snow";
global.__objectNames[137] = "Daylight";
global.__objectNames[138] = "Exit";
global.__objectNames[139] = "Floor";
global.__objectNames[140] = "Lamp";
global.__objectNames[141] = "Lore_Box";
global.__objectNames[142] = "Muzzle_Flash";
global.__objectNames[143] = "Wall";
global.__objectNames[144] = "Teleporter";
global.__objectNames[145] = "Menu_Item_Bug_Report";
global.__objectNames[146] = "Menu_Item_Challenge_Game";
global.__objectNames[147] = "Menu_Item_Challenge_Game_Seeded";
global.__objectNames[148] = "Menu_Item_Close";
global.__objectNames[149] = "Menu_Item_Close_Perk_Help";
global.__objectNames[150] = "Menu_Item_Close_With_Screencap";
global.__objectNames[151] = "Menu_Item_Config_Brightness";
global.__objectNames[152] = "Menu_Item_Config_Debug_Logging";
global.__objectNames[153] = "Menu_Item_Config_Draw_FoW";
global.__objectNames[154] = "Menu_Item_Config_HP_Bar_Color_Shift";
global.__objectNames[155] = "Menu_Item_Config_Show_Alerts";
global.__objectNames[156] = "Menu_Item_Config_Collapse_Event";
global.__objectNames[157] = "Menu_Item_Config_VI_Keyboard";
global.__objectNames[158] = "Menu_Item_Config_Show_Bar_Values";
global.__objectNames[159] = "Menu_Item_Config_Smooth_Rendering";
global.__objectNames[160] = "Menu_Item_Config_Wait_On_FX";
global.__objectNames[161] = "Menu_Item_Config_Full_Screen";
global.__objectNames[162] = "Menu_Item_Divider";
global.__objectNames[163] = "Menu_Item_Do_Not_Open_Lore_Box";
global.__objectNames[164] = "Menu_Item_Exit_Game";
global.__objectNames[165] = "Menu_Item_Full_Heal";
global.__objectNames[166] = "Menu_Item_Select_Tileset";
global.__objectNames[167] = "Menu_Item_Grant_Perk";
global.__objectNames[168] = "Menu_Item_New_Game";
global.__objectNames[169] = "Menu_Item_Open_Character_Sheet";
global.__objectNames[170] = "Menu_Item_Open_Perk_Help_For";
global.__objectNames[171] = "Menu_Item_Open_Perk_Help";
global.__objectNames[172] = "Menu_Item_Open_Conditions_Menu";
global.__objectNames[173] = "Menu_Item_Open_Credits";
global.__objectNames[174] = "Menu_Item_Open_Help";
global.__objectNames[175] = "Menu_Item_Open_Tileset_Menu";
global.__objectNames[176] = "Menu_Item_Open_Highscore";
global.__objectNames[177] = "Menu_Item_Open_Lore_Box";
global.__objectNames[178] = "Menu_Item_Open_Settings";
global.__objectNames[179] = "Menu_Item_Unstable_Portal";
global.__objectNames[180] = "Menu_Item_Win_Game";
global.__objectNames[181] = "Config";
global.__objectNames[182] = "HUD_Game_Staus";
global.__objectNames[183] = "HUD_Player_Status";
global.__objectNames[184] = "HUD_Target_Status";
global.__objectNames[185] = "Log";
global.__objectNames[186] = "Menu";
global.__objectNames[187] = "Menu_Item";
global.__objectNames[188] = "Menu_System";
global.__objectNames[189] = "Object";
global.__objectNames[190] = "Perk";
global.__objectNames[191] = "Player";
global.__objectNames[192] = "Renderer";
global.__objectNames[193] = "Simulation";
global.__objectNames[194] = "Start_Game_Menu";
global.__objectNames[195] = "Start_Challenge_Menu";
global.__objectNames[196] = "Targeting";
global.__objectNames[197] = "Uncarved";
global.__objectNames[198] = "Usable_Object";
global.__objectNames[199] = "Frame_Delay_Light_Updater";
global.__objectNames[200] = "Analytics";
global.__objectNames[201] = "Color_Log";
global.__objectNames[202] = "Debug_Grid_Overlay";
global.__objectNames[203] = "Nemesis";
global.__objectNames[204] = "State_Grid_Overlay";
global.__objectNames[205] = "Condition";
global.__objectNames[206] = "Visibility_Source";
global.__objectNames[207] = "One_Turn_Visibility_Source";
global.__objectNames[208] = "Score_Keeper";
global.__objectNames[209] = "MusicMixer";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for