hp_max = 10.0
hp = 5.0
armor = 0.0
accuracy = 0.0
ranged_accuracy = 0.0
damage = 5.0
ranged_damage = 5.0
hp_regen = 0.0
level = 1.0
xp = 0.0
next_level = 10.0;
prev_level = 0.0;
hit_description = " hit "
hit_description_ranged = " shot "
miss_description = " missed "
ranged_distance_min = 2
ranged_distance_max = 8
ranged_color_start = c_white;
ranged_color_end = c_white;
ranged_fx_ttl = 5;
attacked_this_turn = false;
last_hit_taken = 0;
last_hit_taken_on = 0;
has_been_targetable = false;
burn_duration = 0;
burn_inflictor = noone
no_history = false;
burst = 0;
chaining = false;
seeker_bonus = 0;
charges = false;
charged = false;

